name: Deploy to OVH

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Haciendo deploy
    steps:
      - uses: actions/checkout@v1
      - name: Instalando php y composer
        uses: MilesChou/composer-action@master
        with:
          args: install --ignore-platform-reqs --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
      - run: rm -rf .git
      - run: rm -rf .github
      - run: 'echo "$SSH_KEY" > key'
        shell: bash
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
      - name: 'copy .env'
        run: |
          cp .env.ci .env
          php artisan cache:clear
          php artisan config:clear
          php artisan key:generate
      - name: 'Tests'
        run: composer test
      - run: sudo chmod 700 ./key
      - name: Deploy to OVH
        run: rsync -rav -e "ssh -i ./key -p ${{ secrets.SSH_PORT }} -oStrictHostKeyChecking=no" --progress --exclude={"node_modules","key","storage"} . ${{ secrets.SSH_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.TARGET }}
      - name: 'Remove key'
        run: rm ./key

